/**
 * @file cPathFindingBehaviour.h
 * @author  Kristian Kerrigan <k_kerrigan3@fanshaweonline.ca>
 * @version 1.0
 *
 * @section DESCRIPTION
 *
 * This behaviour will allow an entity to follow a path that is generated by the
 * Dijkstra's or A* Path Following algorithm.
 */

#ifndef _cPathFindingBehaviour_HG_
#define _cPathFindingBehaviour_HG_

#include "iBehaviour.h"
#include "PathingStructs.h"

class cPathFindingBehaviour : public iBehaviour {
public:
	cPathFindingBehaviour();
	virtual ~cPathFindingBehaviour();

	virtual void update(cEntity* pEntity, float deltaTime) override;
	virtual bool isFinished() override;
	virtual void startBehaviour() override;
	virtual void stopBehaviour() override;
	virtual bool isStarted() override;

	glm::vec3 getLastNode();

	void setPath(std::vector<glm::vec3> path);
	void setPath(sPathFinding path);

private:
	int mCurrentNode;
	int mDirection;
	bool mIsFinished;
	std::vector<glm::vec3> mNodes;
};

#endif // !_cDijkstraFollowPathBehaviour_HG_
